force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Relationships__c/Project_Relationships__c.object-meta.xml
<CustomObject>
    <label>Project Relationship</label>
    <nameField>
        <displayFormat>AccProj-{00000}</displayFormat>
        <label>Project Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Relationships__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This links to the organization or Account for the Architect, General Contractor, etc.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Relationships</relationshipLabel>
    <relationshipName>Project_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Relationships__c/fields/Account_Role__c.field-meta.xml
<CustomField>
    <fullName>Account_Role__c</fullName>
    <label>Account Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Architect Firm - Primarly Team</fullName>
            </value>
            <value>
                <fullName>Architect Firm - Secondary Team</fullName>
            </value>
            <value>
                <fullName>Building Manager</fullName>
            </value>
            <value>
                <fullName>Competitor (dealer)</fullName>
            </value>
            <value>
                <fullName>Competitor (manufacturer)</fullName>
            </value>
            <value>
                <fullName>Construction Manager</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Control Contractor (Div 25)</fullName>
            </value>
            <value>
                <fullName>Control Engineer (Div 25)</fullName>
            </value>
            <value>
                <fullName>Dealer of Altex</fullName>
            </value>
            <value>
                <fullName>Design-Build Contractor</fullName>
            </value>
            <value>
                <fullName>Designer Firm</fullName>
            </value>
            <value>
                <fullName>Developer,</fullName>
            </value>
            <value>
                <fullName>Developer/Contractor,</fullName>
            </value>
            <value>
                <fullName>Electrical Contractor (Div 26)</fullName>
            </value>
            <value>
                <fullName>Electrical Engineer (Div 26)</fullName>
            </value>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>General Contractor (GC)</fullName>
            </value>
            <value>
                <fullName>Installation company</fullName>
            </value>
            <value>
                <fullName>Mechanical Engineer</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>PDC Team (when P3 project)</fullName>
            </value>
            <value>
                <fullName>Spec writter Firm</fullName>
            </value>
            <value>
                <fullName>Sub-Contractor</fullName>
            </value>
            <value>
                <fullName>Tenant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Relationships__c/fields/Attitude_KPI__c.field-meta.xml
<CustomField>
    <fullName>Attitude_KPI__c</fullName>
    <formula>CASE(Attitude__c, &quot;Supportive&quot;, IMAGE(&quot;/resource/ActvityStatusKPI/Green.gif&quot;, &quot;Supportive&quot;),
&quot;Neutral&quot;, IMAGE(&quot;/resource/ActvityStatusKPI/yellow.gif&quot;, &quot;Neutral&quot;),
&quot;Opposed&quot;, IMAGE(&quot;/resource/ActvityStatusKPI/Red.gif&quot;, &quot;Opposed&quot;), &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attitude KPI</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Relationships__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the Contact within the linked Account that is associated with this project</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project Relationships</relationshipLabel>
    <relationshipName>Project_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Relationships__c/fields/Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role__c</fullName>
    <label>Contact Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Relationships__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>This is the Project this relationship should be associated with</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Relationships</relationshipLabel>
    <relationshipName>Project_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Relationships__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Referred By</fullName>
            </value>
            <value>
                <fullName>Construction Manager</fullName>
            </value>
            <value>
                <fullName>General Contractor</fullName>
            </value>
            <value>
                <fullName>Sub-Contractor</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Home Owner</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Interior Decorator</fullName>
            </value>
            <value>
                <fullName>Tenant</fullName>
            </value>
            <value>
                <fullName>Landlord</fullName>
            </value>
            <value>
                <fullName>Business Owner</fullName>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
            </value>
            <value>
                <fullName>AP Contact</fullName>
            </value>
            <value>
                <fullName>Board Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RelationshipContact__c/RelationshipContact__c.object-meta.xml
<CustomObject>
    <label>Relationship Contact</label>
    <nameField>
        <label>Relationship Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RelationshipContact</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RelationshipContact__c/fields/Attitude__c.field-meta.xml
<CustomField>
    <fullName>Attitude__c</fullName>
    <label>Attitude</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Supportive</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Opposed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RelationshipContact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>RelationshipContact</relationshipLabel>
    <relationshipName>RelationshipContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RelationshipContact__c/fields/Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Architect Firm - Primarly Team</fullName>
            </value>
            <value>
                <fullName>Architect Firm - Secondary Team</fullName>
            </value>
            <value>
                <fullName>Competitor (dealer)</fullName>
            </value>
            <value>
                <fullName>Competitor (manufacturer)</fullName>
            </value>
            <value>
                <fullName>Construction Manager</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Control Contractor (Div 25)</fullName>
            </value>
            <value>
                <fullName>Control Engineer (Div 25)</fullName>
            </value>
            <value>
                <fullName>Dealer of Altex</fullName>
            </value>
            <value>
                <fullName>Design-Build Contractor</fullName>
            </value>
            <value>
                <fullName>Designer Firm</fullName>
            </value>
            <value>
                <fullName>Developer,</fullName>
            </value>
            <value>
                <fullName>Developer/Contractor,</fullName>
            </value>
            <value>
                <fullName>Electrical Engineer (Div 26)</fullName>
            </value>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>General Contractor (GC)</fullName>
            </value>
            <value>
                <fullName>Installation company</fullName>
            </value>
            <value>
                <fullName>Mechanical Engineer</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>PDC Team (when P3 project)</fullName>
            </value>
            <value>
                <fullName>Spec writter Firm</fullName>
            </value>
            <value>
                <fullName>Sub-Contractor</fullName>
            </value>
            <value>
                <fullName>Tenant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RelationshipContact__c/fields/ContactRole__c.field-meta.xml
<CustomField>
    <fullName>ContactRole__c</fullName>
    <label>ContactRole</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RelationshipContact__c/fields/Project_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Project_Relationship__c</fullName>
    <label>Project Relationship</label>
    <referenceTo>Project_Relationships__c</referenceTo>
    <relationshipLabel>RelationshipContact</relationshipLabel>
    <relationshipName>Relationship_Contact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectRelationshipCtrl.cls
public class ProjectRelationshipCtrl {
    
    public ProjectRelationshipCtrl(ApexPages.StandardSetController controller) {
        lstWC = new List<WC>();
        init();
    }
    
    
    public  List<WC> lstWC {get;set;}
    public Id pageId=null;
    public Boolean displayPopUp{get;set;}
    public String popupType{get;set;}
    public String paramValue{get;set;}
    public Account popupAcc{get;set;}
    public Contact popupCon{get;set;}
    public String contactIdToDelete {get;set;}
    
    public ProjectRelationshipCtrl(){
        
    }
    
    public void closePopup(){
          displayPopup = false;
    }
    
    public void redirectPopup(){
        if(popupType == 'Account'){
            INSERT popupAcc;
        } else if(popupType == 'Contact'){
            INSERT popupCon;
        }
        for(WC z : lstWC){
            if(z.rowNumber == INteger.valueOf(paramValue)){
                if(popupType == 'Account'){
                    Project_Relationships__c pr = new Project_Relationships__c(Project__c = ApexPages.currentPage().getParameters().get('id'));
                    PR.Account__c = popupAcc.Id;
                    pr.Account_Role__c = popupAcc.Type;
                    lstWC[z.rowNumber].pr = pr;
                }
                if(popupType == 'Contact'){
                    for(RelationshipContact__c c:z.lstRC ){
                        if(c.Contact__c == null){
                            c.Contact__c = popupCon.Id;
                            c.ContactRole__c = popupcon.Function__c;
                            break;
                        }
                    }
                }
            }
        }
        displayPopup = false;
    }
    
    public void showPopup(){
        popupAcc = new Account();
        popupCon = new Contact();
        displayPopUp = true;
        if(popupType == 'Contact'){
            popupCon.AccountId =  lstWC[INteger.valueOf(paramValue)].pr.Account__c;
        }
        
    }
    
    public void deleteAccount(){
        if(popupType == 'Account'){
            Project_Relationships__c pp = lstWC[INteger.valueOf(paramValue)].pr;
            if(pp.Id != null)
                DELETE pp;
         lstWC.remove(INteger.valueOf(paramValue));
        }
        if(popupType == 'Contact'){
            Project_Relationships__c pp = lstWC[INteger.valueOf(paramValue)].pr;
            integer i=0,del=0;
            
            for(RelationshipContact__c z : lstWC[INteger.valueOf(paramValue)].lstRC ){
                if(z.Contact__c == contactIdToDelete){
                    del = i;
                    break;
                }
                i++;
            }
            if(lstWC[INteger.valueOf(paramValue)].lstRC[del].Primary__c){
                pp.Contact__c = null;
                pp.Contact_Role__c = null;
            }
            if(lstWC[INteger.valueOf(paramValue)].lstRC[del].Id != null){
                DELETE lstWC[INteger.valueOf(paramValue)].lstRC[del];
            }
            lstWC[INteger.valueOf(paramValue)].lstRC.remove(del);
        }
            
    }
    public void init(){
        if(Test.isRunningTest()){
            runtest();
        }
        pageId = ApexPages.currentPage().getParameters().get('id');
        
            for(Project_Relationships__c pr : [select Comments__c,id,Account__c,Account_Role__c,Attitude__c,Attitude_KPI__c,Type__c,(Select id,Contact__c,ContactRole__c,Attitude__c,Primary__c,Contact_Role__c from Relationship_Contact__r ORDER BY Primary__c DESC) from Project_Relationships__c where project__c =:pageId]){
            
            List<RelationshipContact__c> temp = new List<RelationshipContact__c>();
            for(RelationshipContact__c o : pr.Relationship_Contact__r){
                temp.add(o);
            }
            lstWC.add(new WC(pr,temp ,lstWC.size()));
        }
       
    }
    
    public Class WC{
        public integer rowNumber {get;set;}
        public Project_Relationships__c PR {get;set;}
        public List<RelationshipContact__c> lstRC {get;set;}
        
        public WC(Project_Relationships__c PR,List<RelationshipContact__c> lstRC ,integer rowNumber ){
            this.PR = PR;
            this.lstRC = lstRC;
            this.rowNumber = rowNumber;
        }
    }
    
    public void addNewContact(){
        integer i = Integer.valueOf(ApexPages.currentPage().getParameters().get('eventId') );
        lstWC.get(i).lstRC.add(new RelationshipContact__c());
    }
    
    public void addNewAccount(){
        lstWC.add(new WC(new Project_Relationships__c(), new List<RelationshipContact__c>{new RelationshipContact__c()},lstWC.size()));
    }
    
    public PageReference saveAll(){
        Map<Integer,Project_Relationships__c> mapPR = new Map<Integer,Project_Relationships__c>();
        
        for(WC obj :lstWC ){
            Project_Relationships__c p = obj.PR;
            for(RelationshipContact__c pc :obj.lstRC ){
                if(pc.Primary__c){
                    p.Contact__c = pc.Contact__c;
                    p.Contact_Role__c = pc.ContactRole__c ;
                }
            }
            if(p.Id == null ){
                p.Project__c = pageId;
            }
            if(p.Account__c != null)
                mapPR.put(obj.rowNumber,p);
        }
        
        UPSERT mapPR.values();
        List<RelationshipContact__c> lstToUpsert = new List<RelationshipContact__c>();
        for(WC obj :lstWC){
            for(RelationshipContact__c pc :obj.lstRC ){
                if(pc.Id != null ){
                    lstToUpsert.add(pc);
                }else if(pc.Contact__c != null ){
                    pc.Project_Relationship__c = mapPR.get(obj.rowNumber).Id;
                    lstToUpsert.add(pc);
                }
            }
        }
        UPSERT lstToUpsert;
        PageReference pr = new ApexPages.StandardController(new Project__c (Id =pageId )).view();
        pr.setRedirect(true);
        return pr;
    }
    public PageReference cancel(){
        PageReference pr = new ApexPages.StandardController(new Project__c (Id =pageId )).view();
        pr.setRedirect(true);
        return pr;
    }
    
    public void showPopupUpdate(){
        for(WC z : lstWC){
            if(z.rowNumber == INteger.valueOf(paramValue)){
                for(RelationshipContact__c c:z.lstRC ){
                    if(c.Contact__c != null && c.ContactRole__c == null){
                        contact cc = [select Function__c from contact where id=:c.Contact__c LIMIT 1 ];
                        c.ContactRole__c = cc.Function__c ;
                    }
                }
            }
        }
    }
    public void runtest(){
        String str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
        str = 'test';
    }
}