force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/HasBasisofDesign__c.field-meta.xml
<CustomField>
    <fullName>HasBasisofDesign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HasBasisofDesign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Potential__c.field-meta.xml
<CustomField>
    <fullName>Project_Potential__c</fullName>
    <label>Project Potential</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status shows project status of won, loss, dead, etc.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed - Won</fullName>
            </value>
            <value>
                <fullName>Closed - Lost</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Relationships__c/Project_Relationships__c.object-meta.xml
<CustomObject>
    <label>Project Relationship</label>
    <nameField>
        <displayFormat>AccProj-{00000}</displayFormat>
        <label>Project Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Relationships__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This links to the organization or Account for the Architect, General Contractor, etc.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Relationships</relationshipLabel>
    <relationshipName>Project_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Relationships__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>This is the Project this relationship should be associated with</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Relationships</relationshipLabel>
    <relationshipName>Project_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Relationships__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status defines the current status of this vendor to the project. It tells you if they have the project, influence, etc.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Potential</fullName>
            </value>
            <value>
                <fullName>Probable</fullName>
            </value>
            <value>
                <fullName>Apparent</fullName>
            </value>
            <value>
                <fullName>Influencer</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Blacklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Relationships__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Referred By</fullName>
            </value>
            <value>
                <fullName>Construction Manager</fullName>
            </value>
            <value>
                <fullName>General Contractor</fullName>
            </value>
            <value>
                <fullName>Sub-Contractor</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Home Owner</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Interior Decorator</fullName>
            </value>
            <value>
                <fullName>Tenant</fullName>
            </value>
            <value>
                <fullName>Landlord</fullName>
            </value>
            <value>
                <fullName>Business Owner</fullName>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
            </value>
            <value>
                <fullName>AP Contact</fullName>
            </value>
            <value>
                <fullName>Board Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectMetricsCalcType__c/ProjectMetricsCalcType__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ProjectMetricsCalcType</label>
</CustomObject>

force-app/main/default/classes/CommonHandler.cls
/*
    Project Relationship 
    Total Projects -> COUNT() Project Relationship 
    TotalofProjectsAwarded__c -> 
    
    TEST Class :- CopyProjectRelationshipsTest

*/

public class CommonHandler {
    
    // called from ProjectRelationshipsTrigger 
    public static void ProcessAccount(Set<Id> afterUpdate){
        
        Set<String> uniquecheck = new Set<String>();
        List<ProjectMetricsCalcType__c> prmc = [Select id,name,type__c from ProjectMetricsCalcType__c];
        Map<String,String> prmcMap = new Map<String,String>();
        for(ProjectMetricsCalcType__c ps :prmc){
            prmcMap.put(ps.name,ps.type__c);
        }
        Map<Id,Account> AccountCount = new Map<Id,Account>();
        
        for(Id setId : afterUpdate){
            AccountCount.put(setId,new Account(Id= setId,AwardedNumber__c = 0, TotalofProjectsAwarded__c = 0, Total_Projects__c  = 0, AwardedAmount__c = 0, SpecAmount__c= 0, Specd__c = 0));
        }
        
        for(Project_Relationships__c pr : [select Type__c,id,Project__c,Account__c,Status__c,Project__r.Status__c,Project__r.Project_Potential__c,Project__r.HasBasisofDesign__c from Project_Relationships__c where Account__c IN :AccountCount.keyset() and Project__c != null ]){
            string s = String.valueOf(pr.Account__c) + String.valueOf(pr.Project__c);
            Account acc = AccountCount.get(pr.Account__c);
            
            if(!uniquecheck.contains(s))
                acc.Total_Projects__c += 1;
            
            if(pr.Status__c == 'Awarded' && pr.Project__r.Status__c == 'Closed - Won' && !uniquecheck.contains(s) )
                acc.TotalofProjectsAwarded__c += 1; 
                
            if(pr.Status__c == 'Awarded' && pr.Project__r.Status__c == 'Closed - Won' && !uniquecheck.contains(s) && (prmcMap.get('Awarded').contains(pr.Type__c))  )
                acc.AwardedNumber__c += 1; 
            
            if(pr.Status__c == 'Awarded'  && pr.Project__r.Status__c == 'Closed - Won' && pr.Project__r.Project_Potential__c != null && !uniquecheck.contains(s) && (prmcMap.get('Awarded').contains(pr.Type__c)) ){
                acc.AwardedAmount__c += pr.Project__r.Project_Potential__c;
            }
            
            if(pr.Status__c == 'Awarded' && prmcMap.get('Spec').contains(pr.Type__c) && !uniquecheck.contains(s)){
                acc.Specd__c += 1;
            }
            
            if(pr.Status__c == 'Awarded'  && prmcMap.get('Spec').contains(pr.Type__c) && !uniquecheck.contains(s) && pr.Project__r.Project_Potential__c != null ){
                acc.SpecAmount__c += pr.Project__r.Project_Potential__c ;
            }
            
            uniquecheck.add(s);
        }
        
       if(AccountCount.values().size() > 0)
            update AccountCount.values();
    }
    
    // Called from UpdateParentSalesPotential
     public static void ProcessProject(Set<Id> ProjectIds){
         
         Set<Id> accIds = new Set<Id>();
         for(Project_Relationships__c pr : [select Account__c from Project_Relationships__c where Account__c != null and Project__c IN : ProjectIds ]){
             accIds.add(pr.Account__c);
         }
         if(accIds.size() > 0){
             ProcessAccount(accIds);
         }
     }   
}