force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Architect__c.field-meta.xml
<CustomField>
    <fullName>Architect__c</fullName>
    <label>Architect</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <formula>IF (Parent_Project__c=&apos;&apos; , &quot;Parent&quot;,&quot;Child&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Parent is a formula that tells you if this Project is a Parent or Child Project. If this project is linked to a Parent Project then it assumes it is a &quot;Child&quot; Project.</inlineHelpText>
    <label>Parent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Parent_Project__c.field-meta.xml
<CustomField>
    <fullName>Parent_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the Parent or Master project associated with this child project</inlineHelpText>
    <label>Parent Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Potential__c.field-meta.xml
<CustomField>
    <fullName>Project_Potential__c</fullName>
    <label>Project Potential</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Relationships__c/Project_Relationships__c.object-meta.xml
<CustomObject>
    <label>Project Relationship</label>
    <nameField>
        <displayFormat>AccProj-{00000}</displayFormat>
        <label>Project Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Relationships__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This links to the organization or Account for the Architect, General Contractor, etc.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Relationships</relationshipLabel>
    <relationshipName>Project_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Relationships__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the Contact within the linked Account that is associated with this project</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project Relationships</relationshipLabel>
    <relationshipName>Project_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Relationships__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <inlineHelpText>This is the Project this relationship should be associated with</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Relationships</relationshipLabel>
    <relationshipName>Project_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Relationships__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Referred By</fullName>
            </value>
            <value>
                <fullName>Construction Manager</fullName>
            </value>
            <value>
                <fullName>General Contractor</fullName>
            </value>
            <value>
                <fullName>Sub-Contractor</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Home Owner</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Interior Decorator</fullName>
            </value>
            <value>
                <fullName>Tenant</fullName>
            </value>
            <value>
                <fullName>Landlord</fullName>
            </value>
            <value>
                <fullName>Business Owner</fullName>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
            </value>
            <value>
                <fullName>AP Contact</fullName>
            </value>
            <value>
                <fullName>Board Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory
{
    public static testmethod void createProjectTestRecords()
    {
        Account acc = new Account(Name='testAccount');
        insert acc;
        Contact contact = new Contact(LastName='testContact');
        insert contact;
        
        Project__c testProject1 = new Project__c(Name = 'testPro1');
        insert testProject1;
        
        Project_Relationships__c testProjectRelationship1 = new Project_Relationships__c(Account__c=acc.Id, Project__c=testProject1.Id, Contact__c=contact.Id, Comments__c ='testProject1 Target', Type__c='Architect');
        insert testProjectRelationship1;
        
        Project__c testProject2 = new Project__c(Name = 'testPro2', Parent_Project__c = testProject1.Id, Project_Potential__c = 122);
        insert testProject2;
        Project__c testProject3 = new Project__c(Name = 'testPro3', Parent_Project__c = testProject2.Id, Project_Potential__c = 122);
        insert testProject3;
        Project__c testProject4 = new Project__c(Name = 'testPro4', Parent_Project__c = testProject3.Id, Project_Potential__c = 122);
        insert testProject4;
        
        System.assertEquals(4,[select Id from Project_Relationships__c].size());
        System.assertEquals(122,[select Id, Project_Potential__c from Project__c where Parent__c='Parent'].Project_Potential__c);
        
        testProject4.Parent_Project__c = testProject3.Id;
        update testProject4;
        
        System.assertEquals(4,[select Id from Project_Relationships__c].size());
        testProject3.Parent_Project__c = testProject4.Id;
        update testProject3; 
        System.assertEquals(5,[select Id from Project_Relationships__c].size()); 
        delete testProject2;
        System.assertEquals(4,[select Id from Project_Relationships__c].size());
        
    }
    
    public static testmethod void createProjectRelationshopRecords()
    {
        Account acc = new Account(Name='testAccount');
        insert acc;
        Contact contact = new Contact(LastName='testContact');
        insert contact;
        Project__c testProject1 = new Project__c(Name = 'testPro1');
        insert testProject1;
        Project__c testProject2 = new Project__c(Name = 'testPro2', Parent_Project__c = testProject1.Id, Project_Potential__c = 122);
        insert testProject2;
        Project__c testProject3 = new Project__c(Name = 'testPro3', Parent_Project__c = testProject2.Id, Project_Potential__c = 122);
        insert testProject3;
        Project__c testProject4 = new Project__c(Name = 'testPro4', Parent_Project__c = testProject3.Id, Project_Potential__c = 122);
        insert testProject4;
        
        Project_Relationships__c testProjectRelationship1 = new Project_Relationships__c(Account__c=acc.Id, Project__c=testProject1.Id, Contact__c=contact.Id, Comments__c ='testProject1 Target', Type__c='Architect');
        Project_Relationships__c testProjectRelationship2 = new Project_Relationships__c(Account__c=acc.Id, Project__c=testProject1.Id, Contact__c=contact.Id, Comments__c ='testProject2 core', Type__c='Architect');
        Project_Relationships__c testProjectRelationship3 = new Project_Relationships__c(Account__c=acc.Id, Project__c=testProject1.Id, Contact__c=contact.Id, Comments__c ='testProject3 Target', Type__c='Architect');
        
        
        insert new Project_Relationships__c[] {testProjectRelationship1, testProjectRelationship2, testProjectRelationship3};
        System.assertEquals('testAccount',[select Id, Architect__c, (select Id from Project_Relationships__r)from Project__c].get(0).Architect__c);
        
        Project_Relationships__c testProjectRelationship4 = new Project_Relationships__c(Account__c=acc.Id, Project__c=testProject1.Id, Contact__c=contact.Id, Comments__c ='testProject1 Target', Type__c='General Contractor');
        Project_Relationships__c testProjectRelationship5 = new Project_Relationships__c(Account__c=acc.Id, Project__c=testProject1.Id, Contact__c=contact.Id, Comments__c ='testProject2 core', Type__c='General Contractor');
        Project_Relationships__c testProjectRelationship6 = new Project_Relationships__c(Account__c=acc.Id, Project__c=testProject1.Id, Contact__c=contact.Id, Comments__c ='testProject3 Target', Type__c='General Contractor');
        insert new Project_Relationships__c[] {testProjectRelationship4, testProjectRelationship5, testProjectRelationship6};
        System.assertEquals('testAccount',[select Id, Architect__c, (select Id from Project_Relationships__r)from Project__c].get(0).Architect__c);
        
        CommonHandler.ProcessProject(new set<Id>{testProject1.Id});
        
        update new Project_Relationships__c[]{testProjectRelationship1,testProjectRelationship2};
        delete new Project_Relationships__c[]{testProjectRelationship1,testProjectRelationship2};
        
        
    }
}